INSERT INTO "Ingredient" ("name", "nutritionalValue", "unitID")
VALUES ('Milk', 100, 3),
       ('Egg', 100, 2),
       ('Butter', 150, 1),
       ('Salt', 1, 1),
       ('Bread', 150, 4),
       ('Chicken thigh', 100, 1),
       ('Breadcrumbs', 1, 1),
       ('Rice', 100, 3),
       ('Pepper', 1, 1),
       ('Cheese', 150, 1),
       ('Sriracha', 1, 4),
       ('Ham', 150, 1),
       ('Tortilla', 100, 4),
       ('Flour', 50, 1),
       ('Lime', 1, 5),
       ('Sugar cube', 4, 1),
       ('White rum', 20, 2),
       ('Gin', 20, 2),
       ('Tonic', 400, 2),
       ('Lemon', 1, 5),
       ('Carrot', 20, 1),
       ('Cucumber', 200, 1),
       ('Salad', 20, 1),
       ('Tomato', 50, 1);


INSERT INTO "Category" ("name", "description", "color")
VALUES ('Cakes', 'Delicious cakes', -20561),
       ('Main meals', 'More complex meals, suitable to lunch or dinner', -16776961),
       ('Breakfast', 'Morning makes a day, great breakfast that will start your day in great manner', -16711936),
       ('Small evening snacks', 'When you arent that hungry, but you want to eat something', -65536),
       ('Drinks', 'Shaken, mixed, iced, whatever you need', -16711681),
       ('Vegetable', 'Healthy and tasty', -16711936);

INSERT INTO "Recipe" ("name", "description", "instructions", "categoryID", "portions", "duration")
VALUES ('Tortilla with chicken', 'Fresh burrito in mexican style',
        'Fry the chicken, fill the tortilla with vegetables of your choice, add cheese, salt and pepper to taste and finish with the drizzle of sriracha',
        2, 1, 25),
       ('Scrambled eggs', 'Classic breakfast meal that everybody knows',
        'Mix the eggs with salt and pepper and cook them on the pan until the consistency is what you like. Serve with bread and optionally sriracha',
        3, 2, 20),
       ('Chicken with rice', 'Tasty lunch for whole family',
        'Marinate chicken in the salt pepper, yoghurt and sriracha overnight, then fry it on really hot pan. Cook the rice in ricecooker and serve with the dish, dont forget to salt to taste',
        2, 4, 45),
       ('Birthday cake', 'The main star of the celebration',
        'Well to be hones I dont know how to make birthday cake so I will just throw random stuff to the mixer and hope for the best',
        1, 8, 60),
       ('Toasts', 'Small dinner for everyone to enjoy',
        'Take two slices of bread and spread butter on them. Then toast them in a toaster until the toaster doesnt tell you to stop. Then you can add anything to them. I recommend salami, cheese and ketchupMayo',
        4, 2, 10),
       ('Pancakes', 'Basic pancake recipe to which you can add anything',
        'Mix your flour, milk, salt and egg and create a runny dough. You can also add sugar for sweet pancakes, but it is not necessary. Then put you pan on medium high. Then spread your dough on the pan and cook on each side for 2-3 minutes',
        4, 4, 30),
       ('Mojito', 'The best summer drink',
        'Add lime juice and sugar cube into a glass. Dissolve the sugar cube in the juice. Then add white rum and soda and enjoy.',
        5, 1, 10),
       ('Gin & Tonic', 'The classic', 'Mix Gin and tonic and add some citrus. Preferably lemon.', 5, 1, 10),
       ('Vegetable salad', 'Healthier alternative to meat salads',
        'Just mix it all together in one big bowl. Do not add salt.', 6, 2, 10);


INSERT INTO "IngredientRecipe" ("ingredientID", "recipeID", "amount")
VALUES (4, 1, 1),
       (4, 2, 1),
       (4, 3, 1),
       (5, 2, 1),
       (3, 2, 1),
       (6, 1, 2),
       (6, 3, 3),
       (7, 3, 1),
       (8, 3, 200),
       (9, 1, 1),
       (9, 2, 1),
       (9, 3, 1),
       (10, 1, 1),
       (11, 1, 50),
       (11, 2, 1),
       (11, 3, 1),
       (13, 1, 1),
       (1, 4, 100),
       (2, 4, 4),
       (3, 4, 50),
       (5, 5, 2),
       (3, 5, 1),
       (1, 6, 2),
       (2, 6, 1),
       (4, 6, 1),
       (14, 6, 150),
       (15, 7, 1),
       (16, 7, 1),
       (17, 7, 1),
       (18, 8, 1),
       (19, 8, 1),
       (20, 8, 1),
       (21, 9, 10),
       (22, 9, 30),
       (23, 9, 10),
       (24, 9, 10),
       (4, 9, 1);



